name: "Feature request"
description: "Suggest an idea for RustFrame"
labels: [enhancement]
title: "[Feature]: "
body:
  - type: markdown
    attributes:
      value: "Thanks for the idea!"
  - type: input
    id: version
    attributes:
      label: "Target version (if any)"
      placeholder: "v0.3.0"
  - type: textarea
    id: problem
    attributes:
      label: "Problem"
      description: "What problem does this solve?"
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: "Proposed solution"
      description: "How would you implement it?"
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: "Alternatives considered"
    validations:
      required: false
  - type: textarea
    id: context
    attributes:
      label: "Additional context"
    validations:
      required: false
